In [1]:
import os 
import numpy as np

In [13]:
npz_dir = "/data/base/3M-APP-SCN/02_train/setup04_Evelyn/prediction/CompImBio800M.zarr/luts/fragment_segment"
npz_files = os.listdir(npz_dir)
npz_files

['seg_edges_hist_quant_75_3000.npz',
 'seg_edges_hist_quant_75_1000.npz',
 'seg_edges_hist_quant_75_5000.npz']

In [14]:
for npz_file in npz_files:
    data = np.load(os.path.join(npz_dir, npz_file))
    print(npz_file)
    print(data['fragment_segment_lut'])
    print(len(np.unique(data['fragment_segment_lut'][0])))
    print(len(np.unique(data['fragment_segment_lut'][1])))

seg_edges_hist_quant_75_3000.npz
[[  36879366   64538883   18439683 ... 1705671131 1233615497 3933183892]
 [         0         11          2 ...     878678     878679     878680]]
878681
354834
seg_edges_hist_quant_75_1000.npz
[[  36879366   64538883   18439683 ... 1705671131 1233615497 3933183892]
 [         0          1          2 ...     878678     878679     878680]]
878681
397085
seg_edges_hist_quant_75_5000.npz
[[  36879366   64538883   18439683 ... 1705671131 1233615497 3933183892]
 [         0         11          2 ...     878678     878679     878680]]
878681
319069


In [7]:
npz_file['fragment_segment_lut']

array([[38723354, 38723361, 38723362, ..., 38732174, 38732178, 38732184],
       [       0,        1,        2, ...,     2003,     3452,     2987]],
      dtype=uint64)